#!/bin/bash

################################################################################
# Environment Setup Script for Log Application
# 
# This script will:
# - Detect the server's IP address
# - Create .env file with proper configuration
# - Display connection information
#
# Usage: ./setup-env.sh
################################################################################

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}================================${NC}"
echo -e "${GREEN}Log App Environment Setup${NC}"
echo -e "${GREEN}================================${NC}"
echo ""

# Detect IP address
echo "Detecting server IP address..."
echo ""

# Try to get the primary IP address (excluding localhost)
if command -v ip &> /dev/null; then
    # Linux (Rocky Linux)
    IP_ADDRESS=$(ip route get 1.1.1.1 2>/dev/null | awk '{print $7; exit}')
elif command -v ifconfig &> /dev/null; then
    # macOS/BSD
    IP_ADDRESS=$(ifconfig | grep "inet " | grep -v 127.0.0.1 | awk '{print $2}' | head -n 1)
fi

# Fallback to hostname -I if available
if [ -z "$IP_ADDRESS" ] && command -v hostname &> /dev/null; then
    IP_ADDRESS=$(hostname -I 2>/dev/null | awk '{print $1}')
fi

# If still empty, use localhost
if [ -z "$IP_ADDRESS" ]; then
    IP_ADDRESS="localhost"
    echo -e "${YELLOW}Warning: Could not detect IP address, using localhost${NC}"
else
    echo -e "${GREEN}✓ Detected IP address: $IP_ADDRESS${NC}"
fi

echo ""
echo "Available network interfaces:"
if command -v ip &> /dev/null; then
    ip -4 addr show | grep inet | grep -v 127.0.0.1
else
    ifconfig | grep "inet " | grep -v 127.0.0.1
fi

echo ""
read -p "Enter the IP address to use [$IP_ADDRESS]: " USER_IP
if [ -n "$USER_IP" ]; then
    IP_ADDRESS="$USER_IP"
fi

# Create .env file
echo ""
echo "Creating .env file..."

cat > .env << EOF
# Environment Configuration for Log Application
# Generated by setup-env.sh on $(date)

# Host IP address - Change this to your server's IP address
HOST_IP=$IP_ADDRESS

# Database Configuration
MYSQL_ROOT_PASSWORD=rootpassword
MYSQL_DATABASE=logdb
MYSQL_USER=logapp
MYSQL_PASSWORD=logapp123

# Backend Configuration
PORT=5000
NODE_ENV=production

# Frontend will use: http://\${HOST_IP}:5000/api
EOF

echo -e "${GREEN}✓ .env file created successfully!${NC}"
echo ""

# Display configuration
echo "================================"
echo "Configuration Summary"
echo "================================"
echo "Server IP:        $IP_ADDRESS"
echo "Frontend URL:     http://$IP_ADDRESS:3000"
echo "Backend API:      http://$IP_ADDRESS:5000/api"
echo "Database Port:    3306"
echo ""

echo "================================"
echo "Next Steps"
echo "================================"
echo "1. Review the .env file: cat .env"
echo "2. Start the application: docker compose up -d"
echo "3. Access frontend at: http://$IP_ADDRESS:3000"
echo "4. Access backend API at: http://$IP_ADDRESS:5000/api/health"
echo ""
echo "Note: Make sure firewall ports are open (run: sudo ./open-ports.sh)"
echo ""

exit 0
